name: Update Counter Data

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger
  push:
    paths:
      - 'scraper/**'
    branches:
      - main

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'scraper/package-lock.json'
        
    - name: Install dependencies
      working-directory: ./scraper
      run: npm install
      
    - name: Run scraper
      id: scraper
      working-directory: ./scraper
      run: |
        node src/scraper.js > scraper-output.log 2>&1
        echo "exit_code=$?" >> $GITHUB_OUTPUT
        
    - name: Check if changes were made
      id: check_changes
      run: |
        if git diff --quiet frontend/src/data/units.json; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Create Pull Request
      if: steps.check_changes.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update unit counter data'
        title: '[Automated] Update unit counter data'
        body: |
          ## Automated Counter Data Update
          
          This pull request contains automated updates to the unit counter data scraped from mechamonarch.com.
          
          ### Source
          Data sourced from: https://mechamonarch.com/guide/mechabellum-counters/
          Scraped on: ${{ github.event.repository.updated_at }}
          
          ### Logs
          <details>
          <summary>Scraper output</summary>
          
          ```
          ${{ steps.scraper.outputs.log }}
          ```
          </details>
          
          ---
          *This PR was automatically generated by the Mechabellum counter data scraper.*
        branch: update-counters-${{ github.run_id }}
        delete-branch: true
        labels: |
          automated
          data-update
          
    - name: Upload scraper logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: scraper-logs
        path: |
          scraper/scraper-output.log
          scraper/logs/
          
    - name: Report failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '[Scraper] Failed to update counter data',
            body: `The automated counter data scraper failed to run successfully.
            
            **Run ID**: ${context.runId}
            **Run Number**: ${context.runNumber}
            **Triggered by**: ${context.eventName}
            
            Please check the [workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`,
            labels: ['bug', 'automated']
          })